module.exports = {
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(next/(.*)$)|^(next$)",
    "^(react/(.*)$)|^(react$)",
    "^@radix-ui/(.*)$",
    "contentlayer/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/providers/(.*)$",
    "^@/hooks/(.*)$",
    "^@/libs/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/articles/(.*)$",
    "^@/styles/(.*)$",
    "^@/config/(.*)$",
    "[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    // "prettier-plugin-tailwindcss",
  ],
}
