import { Work_Sans } from "next/font/google"

import Navigation from "@/components/navigation/navigation"

import "../styles/globals.css"

const font = Work_Sans({ subsets: ["latin"] })

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en">
         <body className={font.className}>
            <Navigation />
            {children}
         </body>
      </html>
   )
}
